### ISSUE TITLE
Enable all VM Integration Services for all VMs

### ISSUE THREAD

**Issue by AndreasSobczyk** [Microsoft/ws2016lab#132]

**Comment by jaromirk** [comment]
Why? :) You can copy-item using PSSession to VM. Not needed anymore...

**Comment by AndreasSobczyk** [comment]
Because Copy-vmfile is easier and does not require credentials, so good for lab :)

**Comment by jaromirk** [comment]
OK, these lazy people... Done. Will commit soon.. (I need to bash those other issues you created :D )
