### ISSUE TITLE
Automatically enable static memory when NestedVirt=$true

### ISSUE THREAD

**Issue by AndreasSobczyk** [Microsoft/ws2016lab#133]

**Comment by jaromirk** [comment]
What is the issue here? It will effectively will be static and will use just memorystartupbytes.

**Comment by AndreasSobczyk** [comment]
If static memory is not set, ExposeVirtualizationExtensions is rolled back to false

**Comment by jaromirk** [comment]
Hmm, I just set memorystartupbytes. Weird. Works for me.. Ping me on slack pls, so we can discuss..

**Comment by jaromirk** [comment]
closed due to inactivity
