### ISSUE TITLE
Complete run Deploy Script very soon and no VM be found

### ISSUE THREAD

**Issue by dafoyiming** [Microsoft/ws2016lab#137]
Hi 
Hope this finds you well!

While I am trying to deploy my lab with this 3_deploy script. I found an issue or maybe it is just by design.

Issue: If I set $LABConfig.VMs argument "Configuration"  not equal "S2D", such as "SDN", the script will finished very soon (around 2min without any error) and no VM would be deployed. Compare to use "S2D", everything is doing well as I want.

**Comment by jaromirk** [comment]
By design. There are allowed configurations = simple,s2d,shared,replica … I can change it so it will default to simple. https://github.com/Microsoft/ws2016lab/blob/master/Scripts/3_Deploy.ps1#L1134-L1201
