### ISSUE TITLE
While Creating  SCVMM parent disk, always blocked at step "Installing ADK" 

### ISSUE THREAD

**Issue by dafoyiming** [Microsoft/ws2016lab#141]
Hi 

Hope you're doing well ! While I am trying to creating SCVMM parent disk by CreateParentDisk script, it always block at the step "Install ADK". After I console to the DC Hyper-V VM. It seems no process is running for install ADK. The "Installer" folder is integrallty in the ToolDisk. If I try to run the script named install-adk on the DC directly. It will complete successfully. Something worry? or any workaround?

**Comment by dafoyiming** [comment]
Run "InstalADK" on DC manually and waiting for the install job complete successfully. Then restart the DC vm inside VM is a workaround

**Comment by jaromirk** [comment]
Hmm, what version of ADK? I was recently working with 1709 and it was fine. The code did not change. If you have parent disks, keep it, and just delete dc and run create parent disks again (it takes ~30minutes to "rehydrate"). I'll do the same now

**Comment by jaromirk** [comment]
Weird, works for me 
![image](https://user-images.githubusercontent.com/9829838/38608966-25ef731e-3d7d-11e8-95ba-80f8dad7e47c.png)

**Comment by dafoyiming** [comment]
My ADK Version is also 1709. Let me try you as your proposal. 
😄
