### ISSUE TITLE
Problems on setting up the Hyperconverged S2D with Nano Servers

### ISSUE THREAD

**Issue by TGC-GS** [Microsoft/ws2016lab#4]
Hi,

I have problems on setting up the Hyperconverged S2D with Nano Servers. 
The first issue is an error appearing on the configuration check for the cluster:
![error on check](https://cloud.githubusercontent.com/assets/20063664/16224555/caaaa5d2-37a2-11e6-8327-465c6276179d.png)

Next issue is while I'm trying to set up a storage pool I get the following error:
![cluster-problem1](https://cloud.githubusercontent.com/assets/20063664/16224497/8af8bb18-37a2-11e6-8804-512803d9804e.png)

I checked the physical disks on S2D1 and got the following screen:
![listofdisks](https://cloud.githubusercontent.com/assets/20063664/16224568/e60c8ba6-37a2-11e6-8f6f-7df4d290acd0.png)

So, where I'm doing wrong, I'd be happy if you'd help me out.

Byes
TGC

**Comment by jaromirk** [comment]
you have to create s2d cluster with this command and manually create pool and tiers

#TP5
Enable-ClusterS2D -CimSession $ClusterName -AutoConfig:0 -Confirm:$false -SkipEligibilityChecks

#TP5 fix
Invoke-Command -ComputerName $servers -ScriptBlock {Get-ScheduledTask "SpaceManagerTask" | Disable-ScheduledTask}

#register storage provider 
Get-StorageProvider | Register-StorageSubsystem -ComputerName $ClusterName
   
#create pool
$phydisk = Get-StorageSubSystem -FriendlyName *$ClusterName | Get-PhysicalDisk -CanPool $true
Write-Host "Number of physical disks found:" $phydisk.count -ForegroundColor Cyan

$pool=New-StoragePool -FriendlyName  DirectPool -PhysicalDisks $phydisk -StorageSubSystemFriendlyName *$ClusterName 
$pool | get-physicaldisk | where Size -le 900GB | Set-PhysicalDisk -MediaType SSD
$pool | get-physicaldisk | where Size -ge 900GB | Set-PhysicalDisk -MediaType HDD

#Create Tiers
$Perf = New-StorageTier -FriendlyName Performance  -MediaType SSD -ResiliencySettingName Mirror -StoragePoolFriendlyName $pool.friendlyname  -PhysicalDiskRedundancy 2
$Cap  = New-StorageTier -FriendlyName Capacity     -MediaType HDD -ResiliencySettingName Parity -StoragePoolFriendlyName $pool.friendlyname  -PhysicalDiskRedundancy 2

#create volumes
1..4 | ForEach-Object {
New-Volume -StoragePoolFriendlyName $pool.friendlyname -FriendlyName MultiResiliencyDisk$_ -FileSystem CSVFS_ReFS -StorageTiers $perf,$cap -StorageTierSizes 1TB,10TB
}

**Comment by jaromirk** [comment]
Take a look here https://github.com/Microsoft/ws2016lab/blob/master/Scenarios/S2D%20Hyperconverged%20TP5/s2d_hyperconverged_cluster_TP5.ps1 . I published whole script a minute ago.

**Comment by TolliLF** [comment]
Line 146 - I’d consider using Get-Clusternode in case they don’t call their nodes the same as you.

Tolli Lowell-Forker – Senior PM
Cloud Platform Engineering Center (CPEC)
Enterprise Cloud Group - CAT Team
425.421.1380 | My Calendar [HTML<https://outlook.office365.com/owa/calendar/5227b2b804a2415190096dd895c40261@microsoft.com/85335a745a694a57b6246a90013f4de212348976503993390238/calendar.html>] [ICS<https://outlook.office365.com/owa/calendar/5227b2b804a2415190096dd895c40261@microsoft.com/85335a745a694a57b6246a90013f4de212348976503993390238/calendar.ics>]
TolliL@microsoft.com<mailto:TolliL@microsoft.com>

**Comment by TGC-GS** [comment]
Thank you for your help. First Response helped me out, the enable-clusters2d didn't work for me until you posted your solution. And it's very gentle from you to make a whole script :)
