### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is null

### ISSUE THREAD

**Issue by aadebajo** [Microsoft/ws2016lab#43]
Hi,
I ran the create parent disk script and got this error message at the end.

**Comment by jaromirk** [comment]
Hmm, did you use the latest scripts? Never happened to me. I had some issues few commits ago, but should be fixed. Can you send me log to jaromirk@microsoft.com?

**Comment by jaromirk** [comment]
I just tested it, seems fine
![image](https://user-images.githubusercontent.com/9829838/27769004-13c23004-5f21-11e7-9e4a-de82e04da5b4.png)

[CreateParentDisks.txt](https://github.com/Microsoft/ws2016lab/files/1117730/CreateParentDisks.txt)

**Comment by jaromirk** [comment]
Dev branch seems fine also
[CreateParentDisks.txt](https://github.com/Microsoft/ws2016lab/files/1117758/CreateParentDisks.txt)
![image](https://user-images.githubusercontent.com/9829838/27769379-5dbc9972-5f28-11e7-8599-04899fc03f6c.png)

**Comment by thitluoc20** [comment]
I have same issue

**Comment by thitluoc20** [comment]
![issue](https://user-images.githubusercontent.com/29921830/27866981-f1a23a02-615d-11e7-9397-2b7a750d614b.jpg)

**Comment by jaromirk** [comment]
That's weird - nanoserver vhd is created and core not. What about DC - that one is created? Just trying to figure out what might be wrong.

**Comment by jaromirk** [comment]
Can you please attach log?

**Comment by jaromirk** [comment]
Btw. Install.wim exists under sources on your server media? (maybe there is install.esd instead). I did not check eval media for some time

**Comment by jaromirk** [comment]
Log says it could not find install.wim. Can you check your iso? After you selected it, it was mounted to d:
Cannot find path 'D:\sources\install.wim' because it does not exist.
At G:\scripts\tools\convert-windowsimage.ps1:184 char:39

**Comment by thitluoc20** [comment]
![capture](https://user-images.githubusercontent.com/29921830/27874601-b41d8016-6175-11e7-8546-844d6b859c6d.GIF)
There is no install.wim there. but there is install.swm. Is it the same one ?

**Comment by jaromirk** [comment]
Weird. Where did you get the media from? Ill ask my colleague who owns convert-windowsimage if we can handle this format.

**Comment by thitluoc20** [comment]
I got it in my company's file server. I will ask for other one I try again. Thank you

**Comment by aadebajo** [comment]
Hi Jaromir,

The issue i had was as a result of the fact that i used the windows server
iso i downloaded sometime last year, after downloading a fresh one it
worked and i have been able to start the DC although i still got the
attached error.

Regards

Ademola

**Comment by jaromirk** [comment]
Folks, thanks for heads up! I'll modify the scripts with check, if wim exists. Evan media should contain just install.wim. If you run into any other issues, please let me know. Or if you would like to see some features. If you have any question, just ping me on my mail or here.

**Comment by jaromirk** [comment]
I committed fix dev branch https://github.com/Microsoft/ws2016lab/blob/dev/scripts.zip . It will tell you, that script did not find install.wim and that you should use different media. 

THX! and let me know if anything else!
