### ISSUE TITLE
red text during 2_CreateParentDisks.ps1

### ISSUE THREAD

**Issue by thitluoc20** [Microsoft/ws2016lab#44]
Please tell it is OK or not ?
![error1](https://user-images.githubusercontent.com/29921830/27881850-cd243806-618f-11e7-800f-7e153e5e4856.jpg)
![error2](https://user-images.githubusercontent.com/29921830/27881851-cd29459e-618f-11e7-9876-8a8844f1fb78.jpg)

Thank you

**Comment by thitluoc20** [comment]
![error3](https://user-images.githubusercontent.com/29921830/27882051-bcb4adf6-6190-11e7-9f88-87cb83098ded.jpg)
Should I wait for it until it is end ?
Thank you

**Comment by jaromirk** [comment]
Not OK. This sometimes happens (DISM issue = mounting vhd into directory). Start hydration from the scratch in another directory. What is the filesystem? I had issues with ReFS, I had to go back to NTFS. Also if you are doing it on cluster, on CSV DISM does not work.

**Comment by jaromirk** [comment]
Waiting does not help. The configuration never started. the DC vhd was never modified. The mof files (red errors) are configuration for DSC. Just close window, unmount VHD in diskmgmt (if loaded), unmount ISOs. Start in another directory as DISM somehow remembers it (not sure if NTFS mountpoint stays there)

**Comment by thitluoc20** [comment]
hi, my is filesystem is NTFS and I am using standalone server. Anyway, I will retry again now. Thank you
Huy

**Comment by jaromirk** [comment]
Great! let me knows how it works. Key is different directory as you need different mount Directory.

**Comment by jaromirk** [comment]
Hi Huy, how did it go? Was the issue resolved? Can I close it?

**Comment by jaromirk** [comment]
Closing - no response.
