### ISSUE TITLE
Typo in Deploy.ps1

### ISSUE THREAD

**Issue by WillyMoselhy** [Microsoft/ws2016lab#45]
Line 909 in 3_Deploy.ps1 has "some some"

**Comment by jaromirk** [comment]
THX! Great to see someone is reading the scripts 👍 . In next push it will be fixed!

**Comment by WillyMoselhy** [comment]
I’m trying the S2D scenario but I cannot find any instructions after Deploy.ps1, can you help?

**Comment by jaromirk** [comment]
Login to dc and paste the scenario script. As shown here https://m.youtube.com/results?q=ws2016lab&sm=1 - video number 3.

**Comment by WillyMoselhy** [comment]
This is MAGIC! Thanks man, will spend many hours learning from this script.

**Comment by jaromirk** [comment]
Happy to help! I wrote it this way, so anyone can learn from it. I also write labs for Microsoft Premier workshops for SDS and Hyper-V, so if you can attend, you will see labguides based on these scripts. If you like this, please show it to your peers. Jaromir
