### ISSUE TITLE
What is the purpose of this line?

### ISSUE THREAD

**Issue by WillyMoselhy** [Microsoft/ws2016lab#68]
https://github.com/Microsoft/ws2016lab/blob/1957e84ce8e26f1556c2b6d814e2d1249d4e9feb/Scripts/2_CreateParentDisks.ps1#L553

Just placing the unattend.xml file in the Panther should do the job, right?

Note: I'm trying to understand the code rather than claiming this is an actual issue.

**Comment by jaromirk** [comment]
yup, this is not needed. When I was creating this, I was experimenting and trying multiple ways :). Some settings could be applied with Use-WindowsUnattend. But I think in this unattend are settings that requires copy. So this line can be removed as its not used at all. Feel free to experiment more and pull change...

**Comment by jaromirk** [comment]
And thanks for reading the code! 👍

**Comment by WillyMoselhy** [comment]
As a matter of fact I’m using it as a base for something cool! Will let you know when it is ready for sharing.
