### ISSUE TITLE
Proxy credentials

### ISSUE THREAD

**Issue by WillyMoselhy** [Microsoft/ws2016lab#69]
I suggest to include optional configuration to use Proxy with the cmdlets that download Nuget and the DSC Resources.
We can add them in the LabConfig.PS1 and use $PSDefaultParameterValues to apply it if configured, here's an example,
`    if ($labconfig.ProxyServer){ `
`$PSDefaultParameterValues = @{`
`            "*:Proxy" = $labconfig.ProxyServer`
`            "*:ProxyCredential" = $labconfig.ProxyCreds`
`                                    }`
`    }`
https://github.com/Microsoft/ws2016lab/blob/1957e84ce8e26f1556c2b6d814e2d1249d4e9feb/Scripts/1_Prereq.ps1#L495

**Comment by jaromirk** [comment]
Isn't it easier to run it on machine connected to internet directly and then copy over? Just wondering if it makes some sense to make it complex...

**Comment by WillyMoselhy** [comment]
Unfortunately where I work there’s no way to access the Internet without proxy. So I had to work around it.
In a perfect world, there is never a good reason to make things complex.

**Comment by jaromirk** [comment]
If you want it and you tested it (and it works), pull it into DEV :). I don't have proxy server to test with. Thank you!
