### ISSUE TITLE
Error Creating Parent Disks

### ISSUE THREAD

**Issue by aadebajo** [Microsoft/ws2016lab#7]
I encountered so many errors during creating parent disks, kindly assist.
Find attached.

[Create Parent Disks.docx](https://github.com/Microsoft/ws2016lab/files/427173/Create.Parent.Disks.docx)

**Comment by jaromirk** [comment]
Hmm, looks like convert-windowsimage (script that's called during creation of parent disks) has issues creating vhd. Can you check permissions on file system? You will also need to manually disable secure boot on VMs (switch to Microsoft UEFI CA and then disable), or machines will fail to boot.

**Comment by aadebajo** [comment]
Hi Jaromirk,

How do i check the permission on file system? I do not have any VMs created yet but i have disable secure boot on the PC i am using. 
find attached.
![vhd error](https://cloud.githubusercontent.com/assets/21124364/17815679/49aeaed8-662d-11e6-9095-dfe64a061f17.jpg)

**Comment by aadebajo** [comment]
Hi Jaromirk,

Thanks for your assistance.....i have seen what the problem was. I was running the whole thing from an external disk, as soon as i copied it to the internal drive. The script executed perfectly.

**Comment by jaromirk** [comment]
Glad to hear that it worked well! :) Just curious - it was fat32 filesystem, wasn't it? Also give a try to dev branch  - I added some cool stuff such as vTPM, nested virtualization, little bit different config (new file, just one variable). And let me know how it works and what can I make better. THX!

**Comment by aadebajo** [comment]
It was.....will try dev branch when i am done deploying. Meanwhile i ran into another problem

Error: 145

The directory is not empty.

The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log

Deployment Image Servicing and Management tool
Version: 10.0.14300.1000

What am i suppose to do here?

**Comment by jaromirk** [comment]
Can you attach log?

**Comment by aadebajo** [comment]
[Logs.docx](https://github.com/Microsoft/ws2016lab/files/427969/Logs.docx)

**Comment by jaromirk** [comment]
When does it happen (I mean which task - cleanup, 2_createparentdisks,3_deploy)? Can you also please add deploy.log/createparentdisks.log?

**Comment by aadebajo** [comment]
It happens during createparentdisks

[CreateParentDisks.docx](https://github.com/Microsoft/ws2016lab/files/428014/CreateParentDisks.docx)

**Comment by jaromirk** [comment]
It looks like that mountdir in temp folder still contains mounted VHD from last run. Check disk management and unmount vhd. Also delete temp folder and start again. Or just hydrate all from scratch in new folder (1_prereq -> 2_createparentdisks ...)

**Comment by aadebajo** [comment]
Hello, Thanks again......i was able to go a bit further than before. Createparentdisks was almost completing this time
[CreateParentDisks.docx](https://github.com/Microsoft/ws2016lab/files/428315/CreateParentDisks.docx)

**Comment by jaromirk** [comment]
And now you need to disable that Secure Boot I mentioned. In hyperv manager you should see DC that does not start. Go to settings of this Vm, switch Secure Boot to Microsoft UEFI CA, and then disable Secure Boot. The script then finishes. This is working well in RTM bits, so Ill not be fixing it as RTM will be announced at Ignite.

**Comment by jaromirk** [comment]
Btw if you follow the steps in readme, you should see this in step 5 

Step 5 Right-click and run with PowerShell 2_CreateParentDisks.ps1
2_CreateParentDisks.ps1 will check if you have Hyper-V installed, it will prompt you for Windows Server 2016 TP5 ISO file, hydrate parent disks and hydrate Domain Controller.
note: if you have Windows 10 Anniversary Update, DC will fail to start. You need to switch Secure Boot to Microsoft UEFI CA and then disable Secure Boot. This problem is only in TP5 guests. RTM is OK.

**Comment by jaromirk** [comment]
I'm closing this issue. Takeaway is to create better documentation. I would be happy if you want to contribute. THX, Jaromir

**Comment by aadebajo** [comment]
I have finally been able to go through all the steps and my LAB is now up and running.....thanks a lot for your assistance.

**Comment by jaromirk** [comment]
Cool, did you try the S2D Scenario? https://github.com/Microsoft/ws2016lab/tree/master/Scenarios/S2D%20Hyperconverged%20TP5

**Comment by aadebajo** [comment]
Saw the link and I wanted to try, will like this o know if the variables.ps1 without nested virtualization will be ran within the script area we used in deploying the Lab. Then do I need to run all the configuration script on my main DC while others are still powered off?

**Comment by jaromirk** [comment]
I don't get it. Just look on that gif. It explains it....

**Comment by MS-MatthewWalker** [comment]
When you run the deploy script it will handle the tasks on the DC.
